[package]
name = "cetus_lp_locker"
edition = "2024.alpha"

[dependencies]
CetusClmm = { local = "./vendor/cetus-clmm-interface/sui/cetus_clmm", override = true, published-at = "0xc6faf3703b0e8ba9ed06b7851134bbbe7565eb35ff823fd78432baa4cbeaa12e" }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", rev = "mainnet-v1.3.0", override = true, published-at = "0x0fc913b52c377d6676760ade9f3cfa270b3f5fc0d518e8c11c0480e1b14d7b1a" }
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "mainnet-v1.3.0", override = true, published-at = "0xa883e07d89008ce6b35c793903f7cdb3e2f4af404d204d42242cc5c4e48e7e3b" }

[addresses]
cetus_lp_locker = "0x0"
